name: Backend CI/CD
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
jobs:
  build:
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - name: Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: checkout out code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: yarn

      - name: Build dist
        run: yarn run build-ts

      - name: Build dist
        run: yarn run test

      # - name:
      #   run: docker build . -t emmyduruc/e-commerce

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v1
      #   with:
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}

      # - name:
      #   run: docker push emmyduruc/e-commerce

#when the action is triggered