name: Backend CI/CD
#when the action is triggered
on:
  push:
    branches: [master , develop]
  pull_request:
    branches: [master, develop]
jobs:
  build:
    name: build & test
    runs-on: ubuntu-latest
    steps:
      - name: Install nodejs
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: checkout out code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn
      - name: Build dist
        run: yarn run build-ts
